name: building_and_testing_pipeline
on:
  push:
  pull_request:

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: javaSetup
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: mavenTesting
        run: mvn test -Dcheckstyle.skip
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: javaSetup
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: mavenBuild
        run: mvn verify -Dcheckstyle.skip
