name: pipeline
on: push

jobs: 
  cloneDown:
    runs-on: ubuntu-latest
    steps:
      - name: Clone-down
        uses: actions/checkout@v2

      - name: Upload
        uses: actions/upload-artifact@v2
        with: 
          name: code
          path: . 

  build:
    runs-on: ubuntu-latest
    needs: cloneDown
    steps:
      - name: dowload-repo
        uses: actions/download-artifact@v2
        with: 
          name: code
          path: .
